import { pickHostIcon, type HostIcon } from './host-icon-resolve.js';
export type { HostIcon };
export { pickHostIcon };
export declare const IconEllipsisOutline: HostIcon;
export declare const IconSettingsOutline: HostIcon;
export declare const IconArchiveOutline: HostIcon;
export declare const IconBranchOutline: HostIcon;
export declare const IconEditOutline: HostIcon;
export declare const IconTrashOutline: HostIcon;
export declare const IconCheckOutline: HostIcon;
export declare const IconChevronDownOutline: HostIcon;
export declare const IconListPenOutline: HostIcon;
export declare const IconSearchOutline: HostIcon;
export declare const IconCloseFill: HostIcon;
export declare const IconSlidersTwoOutline: HostIcon;
export declare const IconFolderClose: HostIcon;
export declare const IconWorkspaceTreeOutline: HostIcon;
export declare const IconFlatListOutline: HostIcon;
export declare const IconChevronsUpDownOutline: HostIcon;
export declare const IconClockOutline: HostIcon;
export declare const IconArchiveCheckOutline: HostIcon;
/** 0.1.7 的 Menu 会渲染 children。同一版才出现不带尺寸的图标名，旧 Menu 只认 items。 */
export declare function hostMenuRendersChildren(): boolean;
